---

public_facing_hostname: liityntakatalogi.suomi.fi
ckan_site_name: Liityntäkatalogi
ckan_site_logo: /base/images/lika-logo.svg
ckan_featured_orgs:

analytics_server_public_facing_hostname: kapastats01.csc.fi
analytics_site_id: 2
analytics_auth_token: "{{ secret.analytics_auth_token }}"

matomo:
  public_facing_hostname: https://suomi.matomo.cloud
  site_id: 17

sentry:
  dsn: "https://90b0a66fb880b85721506d42c390dadd@o4507260631580672.ingest.de.sentry.io/4507683758080080"
  traces_sample_rate: "0.1"
  profiles_sample_rate: "0.1"
  loader_script: "https://js-de.sentry-cdn.com/90b0a66fb880b85721506d42c390dadd.min.js"

system:
  ubuntu_codename: jammy
  postgresql:
    version: 14

database_ckan:
  host: 127.0.0.1
  port: 5432
  allowed_ip_range: 127.0.0.1/32
  name: ckan_default
  username: ckan_default
  password: "{{ secret.database_ckan_password }}"

nginx:
  alternative_hostnames: api.suomi.fi  www.{{ public_facing_hostname }}
  alternative_hostnames_with_alternative_certificate: katalogiprod01.csc.fi

solr:
  host: 127.0.0.1
  port: 8983
  listen_address: 127.0.0.1

redis:
  host: 127.0.0.1
  port: 6379

ckan_users:
  admin:
    username: admin
    password: "{{ secret.ckan_admin_password }}"
    email: admin@localhost
  harvest:
    username: harvest
    password: "{{ secret.ckan_harvest_password }}"
    email: harvest@localhost
  test:
    username: test
    password: "{{ secret.ckan_test_password }}"
    email: testuser@localhost
  paha:
    username: paha
    password: "{{ secret.ckan_paha_password }}"
    email: paha@localhost

ckan_admins:
  - "{{ ckan_users.admin.username }}"
  - "{{ ckan_users.harvest.username }}"

email_domain: "{{ public_facing_hostname }}"
email:
  smtp_server: localhost
  from: no-reply@{{ email_domain }}
  error_recipient: admin@localhost
  error_from: error@{{ email_domain }}
  contact: palveluvayla@palveluvayla.fi

xroad:
  securityserver:
    host: "vrkkapalp05.csc.fi"
    alias: "vrkkapalp05"
    port: 8443
  client_id: FI.GOV.0245437-2.APICatalogClient
  service_id: FI.ORG.0920632-0.ServiceList
  service_name: api-docs/api
  environment: 'FI'

elk:
  logstash:
    hosts:
      - "kapalogprod01.csc.fi:5044"
      - "kapalogprod02.csc.fi:5044"
      - "kapalogprod03.csc.fi:5044"

content:
  news:
    endpoint_url: "https://palveluhallinta.suomi.fi/api/articles/importantTopical?newsTypes"
    url_template: "https://palveluhallinta.suomi.fi/{language}/ajankohtaista/uutiset/{id}"
    ssl_verify: true

debug_enabled: false

robots_allowed: true

apicatalog_path: "{{ server_path }}/ckanext/ckanext-apicatalog/"

ckan_plugins:
  - apply_permissions_for_service
  - apicatalog
  - sitesearch
  - scheming_datasets
  - scheming_organizations
  - fluent
  - openapi_view
  - apicatalog_pages
  - pages
  - apicatalog_admin_dashboard
  - apicatalog_harvesterstatus
  - harvest
  - xroad_harvester
  - text_view
  - wsdl_view
  - validate_links
  - xroad_integration
  - sentry
  - forcetranslation
  - markdown_editor
  - activity

allowed_user_creators:
  - paha
  - csc_admin

allowed_user_editors:
  - paha
  - csc_admin

allowed_member_editors:
  - csc_admin

developers:
  - user: bzar
  - user: zharktas
  - user: eetumans
    remove: true
