---

public_facing_hostname: liityntakatalogi.test.suomi.fi
ckan_site_name: Liityntäkatalogi
ckan_site_logo: /base/images/lika-logo-test.svg
ckan_featured_orgs: kermitti putki-ville-oy
ckan_test_environment: True

analytics_server_public_facing_hostname: kapastats01.csc.fi
analytics_site_id: 3
analytics_auth_token: "{{ secret.analytics_auth_token }}"

matomo:
  public_facing_hostname: https://suomi.matomo.cloud
  site_id: 16

database_ckan:
  host: 127.0.0.1
  port: 5432
  allowed_ip_range: 127.0.0.1/32
  name: ckan_default
  username: ckan_default
  password: "{{ secret.database_ckan_password }}"

nginx:
  alternative_hostnames: testiliityntakatalogi.csc.fi

solr:
  host: 127.0.0.1
  port: 8983
  listen_address: 127.0.0.1

redis:
  host: 127.0.0.1
  port: 6379

ckan_users:
  admin:
    username: admin
    password: "{{ secret.ckan_admin_password }}"
    email: admin@localhost
  test:
    username: test
    password: "{{ secret.ckan_test_password }}"
    email: testuser@localhost
  paha:
    username: paha
    password: "{{ secret.ckan_paha_password }}"
    email: paha@localhost

ckan_admins:
  - "{{ ckan_users.admin.username }}"

email_domain: "{{ public_facing_hostname }}"
email:
  smtp_server: localhost
  from: no-reply@{{ email_domain }}
  error_recipient: admin@localhost
  error_from: error@{{ email_domain }}
  contact: palveluvayla@palveluvayla.fi

xroad:
  securityserver:
    host: "vrkkapalpt05.csc.fi"
    alias: "vrkkapalpt05"
    port: 443
  client_id: FI-TEST.GOV.0245437-2.APICatalogClient
  service_id: FI-TEST.GOV.0920632-0.ServiceList
  service_name: api-docs/api

elk:
  logstash:
    hosts:
      - "kapalogtest01.csc.fi:5044"
      - "kapalogtest02.csc.fi:5044"
      - "kapalogtest03.csc.fi:5044"

content:
  news:
    endpoint_url: "https://palveluhallinta.test.suomi.fi/api/articles/importantTopical"
    url_template: "https://palveluhallinta.test.suomi.fi/{language}/ajankohtaista/uutiset/{id}"
    ssl_verify: false

debug_enabled: false

robots_allowed: false

apicatalog_ui_path: "{{ server_path }}/ckanext/ckanext-apicatalog_ui/"

ckan_plugins:
  - apicatalog_scheming
  - scheming_datasets
  - scheming_organizations
  - fluent
  - apicatalog_ui
  - openapi_view
  - apicatalog_pages
  - pages
  - apicatalog_admin_dashboard
  - apicatalog_routes
  - contact
  - apicatalog_feed
  - apicatalog_harvesterstatus
  - harvest
  - xroad_harvester
  - text_view
  - wsdl_view
  - validate_links
  - apply_permissions_for_service
  - xroad_integration
  - forcetranslation


allowed_user_creators:
  - paha
  - csc_admin

allowed_user_editors:
  - paha
  - csc_admin

allowed_member_editors:
  - csc_admin
