---

- name: Ensure temp directory for extensions
  file: path={{ ckanext_sync_path }} state=directory

# On servers, create an archive of the current sources, upload and unarchive

- name: Archive extension
  local_action: command zip -FSr /tmp/api-catalog-{{ ckanext }}.zip {{ ckanext }} chdir="../ckanext"
  become: false
  when: deployment_environment_id != "vagrant"

- name: Delete existing extension
  file: path="{{ ckanext_sync_path }}/{{ ckanext }}" state=absent
  when: deployment_environment_id != "vagrant"

- name: Copy and unarchive extension
  unarchive: src=/tmp/api-catalog-{{ ckanext }}.zip dest="{{ ckanext_sync_path }}/" owner=root group=root
  when: deployment_environment_id != "vagrant"

# On Vagrant, symlink sources from host so that they can be edited live

- name: Remove existing extension (Vagrant)
  file: path="{{ ckanext_sync_path }}/{{ ckanext }}" state=absent
  when: deployment_environment_id == "vagrant"

- name: Symlink extension sources from host machine (Vagrant)
  file: src="/vagrant/ckanext/{{ ckanext }}" path="{{ ckanext_sync_path }}/{{ ckanext }}" state=link
  when: deployment_environment_id == "vagrant"

#

# Two conventions in extension requirements files

- name: Register extension requirements.txt
  stat: path="{{ ckanext_sync_path }}/{{ ckanext }}/requirements.txt"
  register: requirements

- name: Register extension pip-requirements.txt
  stat: path="{{ ckanext_sync_path }}/{{ ckanext }}/pip-requirements.txt"
  register: piprequirements

- name: Install extension requirements
  pip: requirements="{{ ckanext_sync_path }}/{{ ckanext }}/requirements.txt" virtualenv={{ virtualenv}} chdir="{{ ckanext_sync_path }}/{{ ckanext }}"
  when: requirements.stat.exists

- name: Install extension piprequirements
  pip: requirements="{{ ckanext_sync_path }}/{{ ckanext }}/pip-requirements.txt" virtualenv={{ virtualenv}}
  when: piprequirements.stat.exists

- block:
    - name: Register extension dev-requirements.txt
      stat: path="{{ ckanext_sync_path }}/{{ ckanext }}/dev-requirements.txt"
      register: devrequirements

    - name: Install extension dev requirements
      pip: requirements="{{ ckanext_sync_path }}/{{ ckanext }}/dev-requirements.txt" virtualenv={{ virtualenv}}
      when: devrequirements.stat.exists
  when: deployment_environment_id == "vagrant"

- name: Link extension sources
  pip:
    virtualenv: "{{ virtualenv }}"
    name: "{{ ckanext_sync_path }}/{{ ckanext }}"
    editable: yes
  notify: Restart CKAN

