---

# Supervisor and other services may block database update and they should be
# stopped here before database upgrade

- name: Stop supervisor services
  shell: supervisorctl stop all

- name: Initialize CKAN database
  shell: ckan db init
  ignore_errors: True

- name: Upgrade CKAN database
  shell: ckan db upgrade
  ignore_errors: True

- name: Upgrade CKAN filestore
  shell: ./bin/paster --plugin=ckan db migrate-filestore "--config={{ ckan_ini }}" chdir={{ virtualenv }}
  ignore_errors: True

- name: Create initial CKAN users
  shell: ./bin/paster --plugin=ckan user add "{{ item.value.username }}" "password={{ item.value.password }}" "email={{ item.value.email }}" "--config={{ ckan_ini }}" chdir={{ virtualenv }}
  ignore_errors: True
  with_dict: "{{ ckan_users }}"

- name: Set CKAN sysadmins
  shell: ./bin/paster --plugin=ckan sysadmin add {{ item }} --config={{ ckan_ini }} chdir={{ virtualenv }}
  ignore_errors: True
  with_items: "{{ ckan_admins }}"

- name: Initialize Harvest database
  shell: ./bin/paster --plugin=ckanext-harvest harvester initdb "--config={{ ckan_ini }}" chdir={{ virtualenv }}

- name: Initialize Link Validation database
  shell: ./bin/paster --plugin=ckanext-validate_links links initdb "--config={{ ckan_ini }}" chdir={{ virtualenv }}

- name: Initialize service permission application database
  shell: ./bin/paster --plugin=ckanext-apply_permissions_for_service apply_permissions init "--config={{ ckan_ini }}" chdir={{ virtualenv }}
  when: "'apply_permissions_for_service' in ckan_plugins"

- name: Initialize users for organization database
  shell: ./bin/paster --plugin=ckanext-apicatalog_routes apicatalog_db init "--config={{ ckan_ini }}" chdir={{ virtualenv }}