---

# Supervisor and other services may block database update and they should be
# stopped here before database upgrade

- name: Stop supervisor services
  shell: supervisorctl stop all

- name: Initialize CKAN database
  shell: ./bin/ckan --config {{ ckan_ini }} db init chdir={{ virtualenv }}
  ignore_errors: True

- name: Upgrade CKAN database
  shell: ./bin/ckan --config {{ ckan_ini }} db upgrade chdir={{ virtualenv }}
  ignore_errors: True

# Not supported in CKAN 2.9
#- name: Upgrade CKAN filestore
#  shell: ./bin/ckan --config {{ ckan_ini }} db migrate-filestore chdir={{ virtualenv }}
#  ignore_errors: True

- name: Create initial CKAN users
  shell: ./bin/ckan --config {{ ckan_ini }} user add "{{ item.value.username }}" "password={{ item.value.password }}" "email={{ item.value.email }}" chdir={{ virtualenv }}
  ignore_errors: True
  with_dict: "{{ ckan_users }}"

- name: Set CKAN sysadmins
  shell: ./bin/ckan --config {{ ckan_ini }} sysadmin add {{ item }} chdir={{ virtualenv }}
  ignore_errors: True
  with_items: "{{ ckan_admins }}"

- name: Initialize Harvest database
  shell: ./bin/ckan --config {{ ckan_ini }} harvester initdb chdir={{ virtualenv }}

- name: Initialize Link Validation database
  shell: ./bin/ckan --config {{ ckan_ini }} links initdb chdir={{ virtualenv }}

- name: Migrate Link Validation database
  shell: ./bin/ckan --config {{ ckan_ini }} links migrate chdir={{ virtualenv }}

- name: Initialize users for organization database
  shell: ./bin/ckan --config "{{ ckan_ini }}" apicatalog-database init chdir={{ virtualenv }}

- name: Initialize xroad database
  shell: ./bin/ckan --config "{{ ckan_ini }}" xroad init-db chdir={{ virtualenv }}

- name: Init and updgrade xroad alembic databases
  shell: ./bin/ckan --config {{ ckan_ini }} db upgrade -p xroad_integration chdir={{ virtualenv }}

- name: Initialize pages database
  shell: ./bin/ckan --config {{ ckan_ini }} pages initdb  chdir={{ virtualenv }}

- name: Migrate apply-permissions database
  shell: ./bin/ckan --config {{ ckan_ini }} db upgrade -p apply_permissions_for_service chdir={{ virtualenv }}
  when: "'apply_permissions_for_service' in ckan_plugins"
