- name: re-minify ckanext-apicatalog_ui module javascript files
  shell: ./bin/paster --plugin=ckan minify "{{ apicatalog_ui_ckanext_path }}/fanstatic/javascript/modules" "--config={{ ckan_ini }}" chdir="{{ virtualenv }}"
  tags:
    - frontend-build

- name: rebuild ckanext-apicatalog_ui less
  shell: lessc "{{ apicatalog_ui_path }}/less/main.less" "{{ apicatalog_ui_ckanext_path }}/fanstatic/main.css"

- name: Start CKAN
  uri:
    url: "http://127.0.0.1:8080"
