- name: rebuild ckanext-apicatalog sass
  shell: sass "{{ apicatalog_path }}/scss/main.scss"  "{{ apicatalog_ckanext_path }}/fanstatic/apicatalog/main.css"

- name: rebuild ckanext-openapi_view sass
  shell: sass "{{ apicatalog_path }}/scss/openapi_view.scss"  "{{ apicatalog_ckanext_path }}/fanstatic/openapi_view.css"

- name: Restart CKAN
  shell: supervisorctl restart "{{ ckan_supervisor_name }}"

- name: Verify CKAN is running
  uri:
    url: "http://127.0.0.1:8080"
