---

- name: Remove Python 2 packages
  apt:
    package:
      - python-pip
      - python-dev
      - python-virtualenv
      - python-psycopg2
    state: absent

- name: Install Python 3 packages
  apt:
    package:
      - python3
      - python3-pip
      - python3-dev
      - python3-virtualenv
      - python3-psycopg2
      - virtualenv