# For local use only

#- name: Copy MySQL configuration
#  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf mode="0644" owner=root group=root

- name: Add Piwik MySQL database
  mysql_db: name="piwik" state="present" login_user="root" login_password=""

- name: Add piwik MySQL user
  mysql_user: name="piwik" state="present" password="{{ secret.database_piwik_password }}" login_user="root" login_password="" priv="piwik.*:ALL"

- name: Restart MySQL
  service: name=mysql state=restarted

- name: Check if piwik is already installed
  stat: path=/var/www/piwik
  register: piwik_install

- name: Download piwik
  get_url: url=http://builds.piwik.org/piwik-3.0.2.zip dest=/tmp/piwik-3.0.2.zip
  when: not piwik_install.stat.exists

- name: Extract piwik
  unarchive: src=/tmp/piwik-3.0.2.zip dest=/opt copy=no owner=www-data group=www-data
  when: not piwik_install.stat.exists

- name: Copy apache configuration
  template: src=apache_piwik.conf.j2 dest=/etc/apache2/sites-available/piwik.conf mode="0644" owner=root group=root

- name: Enable Apache configuration
  file: src=/etc/apache2/sites-available/piwik.conf dest=/etc/apache2/sites-enabled/piwik.conf state=link owner=root group=root

- name: Disable default Apache configuration
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Restart Apache
  service: name=apache2 state=restarted

- name: Copy Nginx configuration
  template: src=nginx_piwik.j2 dest=/etc/nginx/sites-available/piwik
  when: deployment_environment_id == "vagrant"

- name: Enable Nginx configuration
  file: src=/etc/nginx/sites-available/piwik dest=/etc/nginx/sites-enabled/piwik state=link owner=root group=root
  when: deployment_environment_id == "vagrant"

- name: Restart Nginx
  service: name=nginx state=restarted

