---
# handlers file for mailhog

- name: restart mailhog
  systemd:
    name: mailhog
    state: restarted

- name: restart mailhog and run daemon reload
  systemd:
    name: mailhog
    state: restarted
    daemon_reload: true
