---
# tasks file for mailhog

- name: Create group for mailhog user
  group:
    name: mailhog
    system: true
    state: present

- name: Create mailhog user
  user:
    name: mailhog
    system: true
    create_home: false
    state: present


- name: Ensure mailhog directory exists
  file:
    path: "{{ mailhog_install_dir }}"
    owner: mailhog
    group: mailhog
    state: directory
    mode: 0755

- name: Download mailhog and mhsendmail
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: mailhog
    group: mailhog
    mode: 0755
  with_items:
    - url: "{{ mailhog_release_url }}"
      dest: "{{ mailhog_install_dir }}/mailhog"
    - url: "{{ mailhog_mhsendmail_release_url }}"
      dest: "{{ mailhog_install_dir }}/mhsendmail"
  notify: restart mailhog

- name: Create systemd service file for mailhog
  template:
    src: mailhog.service.j2
    dest: /etc/systemd/system/mailhog.service
    owner: root
    group: root
    mode: 0644
  notify: restart mailhog and run daemon reload

- name: Enable and start mailhog service
  systemd:
    name: mailhog
    state: started
    enabled: true
    daemon_reload: true
