---

- name: Ensure Nginx is installed
  apt: pkg=nginx state=latest

- name: Ensure snippet directory
  file: path="/etc/nginx/snippets" state=directory mode="0775" owner=root group=root

- name: Copy base Nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode="0644" owner=root group=root

- name: Copy Nginx sites
  template: src={{ item.template }} dest=/etc/nginx/{{ item.destination }} mode="0644" owner=root group=root
  with_items:
    - { "template": "nginx_site_config.j2", "destination": "sites-available/primary_site" }
    - { "template": "nginx_security_headers.conf.j2", "destination": "snippets/nginx_security_headers.conf" }

- name: Ensure static resource directory
  file: path="{{ static_path }}" state=directory mode="0775" owner=root group=root

- name: Copy static resources
  copy: src={{ item.src }} dest={{ static_path }}/{{ item.dest }} mode="0644" owner=root group=root
  with_items:
    - { "src": "50x.html", "dest": "50x.html" }

- name: Ensure static file permissions
  command: chmod -R "0775" "{{ static_path }}"

- name: Disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Enable Nginx site
  file: src="/etc/nginx/sites-available/{{ item }}" dest="/etc/nginx/sites-enabled/{{ item }}" state=link
  with_items:
    - primary_site
  notify: Restart Nginx

- name: Ensure Nginx is restarted
  service: name=nginx state=restarted
