---

# To run:
# ansible-playbook -v -i inventories/vagrant deploy-all.yml
# ansible-playbook --ask-vault-pass -v -i inventories/qa deploy-all.yml

- hosts: mainserver
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - os-base
    - java8
    - postgres
    - postgres-backup
    - solr6
    - redis
    - ssl
    - nginx
    - apache
    - postfix
    - { role: ckan-extension, ckanext: ckanext-apicatalog_routes }
    - { role: ckan-extension, ckanext: ckanext-apicatalog_scheming }
    - { role: ckan-extension, ckanext: ckanext-apicatalog_ui }
    - { role: ckan-extension, ckanext: ckanext-fluentall }
    - { role: ckan-extension, ckanext: ckanext-scheming }
    - { role: ckan-extension, ckanext: ckanext-fluent }
    - { role: ckan-extension, ckanext: ckanext-pages }
    - { role: ckan-extension, ckanext: ckanext-contact }
    - { role: ckan-extension, ckanext: ckanext-harvest }
    - { role: ckan-extension, ckanext: ckanext-xroad_integration }
    - { role: ckan-extension, ckanext: ckanext-validate_links }
    - { role: ckan-extension, ckanext: ckanext-saha }
    - { role: ckan-extension, ckanext: ckanext-paha }
    - { role: ckan-ui }
    - ckan
    - ckan-translations
    - supervisor
    - solr-reindex
    - filebeat
  handlers:
    - include: handlers/handlers.yml
