---

# Updates the source codes of a single CKAN extension. This does not do a
# complete deployment and thus only works if a deploy-all has been run
# beforehand.

# To run:
# ansible-playbook -v -i inventories/vagrant -e ckanext=ckanext-apicatalog update-extension.yml
# ansible-playbook --ask-vault-pass -v -i inventories/qa -e ckanext=ckanext-apicatalog update-extension.yml

- hosts: mainserver
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - ckan-extension
  handlers:
    - import_tasks: handlers/handlers.yml