---

- name: Ensure Jetty is not installed
  apt: pkg={{ item }} state=absent
  with_items:
    - jetty
    - libjetty-extra-java

- name: Check if solr3 jetty service exists
  stat: path=/etc/init.d/jetty
  register: jetty_exists


- name: Stop solr3 jetty
  service: name=jetty state=stopped
  when: jetty_exists.stat.exists

- name: Create paths
  file: path={{ item }} state=directory mode="0775" owner=root group=root
  with_items:
      - "{{ cache_path }}/solr"
      - "/opt/solr/"

- name: Download Solr package
  get_url: url={{ solr_download_url }} dest={{ cache_path }}/solr/solr-{{ solr_version }}.zip mode="0644" owner=root group=root
  register: fetch_solr

- name: Extract Solr installer from the archive
  unarchive: src={{ cache_path }}/solr/solr-{{ solr_version }}.zip dest={{ cache_path }}/solr copy=no
  when: fetch_solr is changed

- name: Install Solr
  command: "{{ cache_path }}/solr/solr-{{ solr_version }}/bin/install_solr_service.sh  {{ cache_path }}/solr/solr-{{ solr_version }}.zip -d /var/solr -u {{ solr_user }} -s solr -p 8983 -i /opt/solr -f"
  become: true
  when: fetch_solr is changed

- name: Start solr
  service: name=solr state=started
  when: fetch_solr is changed

- name: Create Solr core
  command: "/opt/solr/solr/bin/solr create -c ckan"
  become: true
  become_user: solr
  when: fetch_solr is changed

- name: Copy CKAN Solr schema
  copy: src=schema.xml dest=/var/solr/data/ckan/conf/managed-schema mode="0644" owner=solr group=solr
  become: true
  become_user: solr

# Can be removed once solr is updated to 8.11.1
- name: Configure solr opts
  lineinfile:
    path: /etc/default/solr.in.sh
    state: present
    line: 'SOLR_OPTS="$SOLR_OPTS -Dlog4j2.formatMsgNoLookups=true"'
    search_string: 'log4j2.formatMsgNoLookups=true'

- name: Restart solr
  service: name=solr state=restarted
