name: Code Quality

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 ckanext --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan
      - name: Run flake8
        run: flake8 ckanext --count --max-line-length=127 --statistics --exclude ckan
  test:
    name: Test apicatalog extensions
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:2.11
      options: --user root  # https://github.com/actions/checkout/issues/956
    services:
      solr:
        image: ckan/ckan-solr:2.11-solr9
      postgres:
        image: ckan/ckan-postgres-dev:2.11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install requirements
        run: |
          cd ckanext/ckanext-apicatalog
          pip install -r dev-requirements.txt
          pip install -e .

          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini

          cd ../ckanext-scheming
          pip install -e .

          cd ../ckanext-fluent
          pip install -e .

          cd ../ckanext-markdown_editor
          pip install -e .

          cd ../ckanext-apply_permissions_for_service
          pip install -e .

          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini

      - name: Setup extension
        run: |
          ckan -c ckanext/ckanext-apicatalog/test.ini db init

      - name: Run tests
        run: |
          pytest --ckan-ini=ckanext/ckanext-apicatalog/test.ini --cov=ckanext.apicatalog --cov-report xml:apicatalog.xml --disable-warnings ckanext/ckanext-apicatalog/ckanext/apicatalog/tests
          pytest --ckan-ini=ckanext/ckanext-apply_permissions_for_service/test.ini --cov=ckanext.apply_permissions_for_service --disable-warnings ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/tests

      - name: install codecov requirements
        if: ${{ !cancelled() }}
        run: |
          apt-get update
          apt-get install -y curl gpg

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./apicatalog.xml

  text-xroad:
    name: Test xroad integration
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:2.11
      options: --user root  # https://github.com/actions/checkout/issues/956
    services:
      solr:
        image: ckan/ckan-solr:2.11-solr9
      postgres:
        image: ckan/ckan-postgres-dev:2.11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
      - name: Add build dependencies to container
        run: |
          apt install \
          tar
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: /root/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install xroad integration requirements
        run: |

          cd ckanext/ckanext-apicatalog
          pip install -r dev-requirements.txt
          pip install -e .

          cd ../ckanext-harvest
          pip install -r pip-requirements.txt
          pip install -e .

          cd ../ckanext-scheming
          pip install -e .

          cd ../ckanext-fluent
          pip install -e .

          cd ../ckanext-markdown_editor
          pip install -e .

          cd ../ckanext-xroad_integration
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install -e .

          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini

      - name: setup xroad integration extension
        run: |
          # Enable plugins in test.ini temporarily
          sed -i -e 's/#ckan.plugins/ckan.plugins/' ckanext/ckanext-xroad_integration/test.ini
          
          ckan -c ckanext/ckanext-xroad_integration/test.ini db init
          ckan -c ckanext/ckanext-xroad_integration/test.ini db upgrade -p harvest
          ckan -c ckanext/ckanext-xroad_integration/test.ini xroad init-db

      - name: Run xroad integration tests
        run: pytest --ckan-ini=ckanext/ckanext-xroad_integration/test.ini --cov=ckanext.xroad_integration --disable-warnings ckanext/ckanext-xroad_integration/ckanext/xroad_integration/tests
