name: Code Quality

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 ckanext --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan
      - name: Run flake8
        run: flake8 ckanext --count --max-line-length=127 --statistics --exclude ckan
  test:
    name: Test apicatalog extensions
    runs-on: ubuntu-latest
    container:
      image: openknowledge/ckan-dev:2.9
    services:
      solr:
        image: ckan/ckan-solr-dev:2.9
      postgres:
        image: ckan/ckan-postgres-dev:2.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install requirements
        run: |
          cd ckanext/ckanext-apicatalog_routes
          pip install -r dev-requirements.txt
          pip install -e .
          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini

          cd ../ckanext-apicatalog_ui
          pip install -e .

          cd ../ckanext-scheming
          pip install -e .

          cd ../ckanext-apicatalog_scheming
          pip install -e .
          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini

          cd ../ckanext-fluent
          pip install -e .

      - name: Setup extension
        run: |
          ckan -c ckanext/ckanext-apicatalog_routes/test.ini db init
      - name: Run tests
        run: |
          pytest --ckan-ini=ckanext/ckanext-apicatalog_routes/test.ini --cov=ckanext.apicatalog_routes --disable-warnings ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/tests
          pytest --ckan-ini=ckanext/ckanext-apicatalog_scheming/test.ini --cov=ckanext.apicatalog_scheming --disable-warnings ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/tests
